name = "UncertainEvidence"
uuid = "1a86d166-648f-46fd-af52-fbd54890c8f1"
version = "0.2.1"
authors = ["Lorenz Gillner <lorenz.gillner@hs-wismar.de"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[weakdeps]
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"

[extensions]
UncertainEvidenceIntervalArithmeticExt = "IntervalArithmetic"

[compat]
Combinatorics = "1.1.0"
IntervalArithmetic = "1.0.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
