name = "UncertainEvidence"
uuid = "1a86d166-648f-46fd-af52-fbd54890c8f1"
authors = ["Lorenz Gillner <lorenz.gillner@hs-wismar.de"]
version = "0.1.2"

[compat]
julia = "1.6"

[extras]
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LazySets", "LinearAlgebra", "Test"]